#!/bin/bash
set -e

#DEBHELPER#

if [ "$1" = "configure" ]; then
    if [ ! -d "/var/lib/karaage-admin/static" ]; then
        django-admin collectstatic --settings=kgadmin.conf.settings --noinput
    fi
fi

if [ "$1" = "triggered" ]; then
    if [ "$2" = "karaage-static" ]; then
        django-admin collectstatic --settings=kgadmin.conf.settings --noinput
    fi
fi

